package org.kexie.bookshelfbackyard.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.kexie.bookshelfbackyard.model.UserWechat;
import org.kexie.bookshelfbackyard.model.UserWechatExample;

@Mapper
public interface UserWechatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatUser
     *
     * @mbg.generated Sat Sep 25 20:51:01 CST 2021
     */
    long countByExample(UserWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatUser
     *
     * @mbg.generated Sat Sep 25 20:51:01 CST 2021
     */
    int deleteByExample(UserWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatUser
     *
     * @mbg.generated Sat Sep 25 20:51:01 CST 2021
     */
    int deleteByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatUser
     *
     * @mbg.generated Sat Sep 25 20:51:01 CST 2021
     */
    int insert(UserWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatUser
     *
     * @mbg.generated Sat Sep 25 20:51:01 CST 2021
     */
    int insertSelective(UserWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatUser
     *
     * @mbg.generated Sat Sep 25 20:51:01 CST 2021
     */
    List<UserWechat> selectByExample(UserWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatUser
     *
     * @mbg.generated Sat Sep 25 20:51:01 CST 2021
     */
    UserWechat selectByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatUser
     *
     * @mbg.generated Sat Sep 25 20:51:01 CST 2021
     */
    int updateByExampleSelective(@Param("record") UserWechat record, @Param("example") UserWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatUser
     *
     * @mbg.generated Sat Sep 25 20:51:01 CST 2021
     */
    int updateByExample(@Param("record") UserWechat record, @Param("example") UserWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatUser
     *
     * @mbg.generated Sat Sep 25 20:51:01 CST 2021
     */
    int updateByPrimaryKeySelective(UserWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatUser
     *
     * @mbg.generated Sat Sep 25 20:51:01 CST 2021
     */
    int updateByPrimaryKey(UserWechat record);
}