package org.kexie.bookshelfbackyard.model.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.kexie.bookshelfbackyard.model.BookingRecord;
import org.kexie.bookshelfbackyard.model.BookingRecordExample;

public interface BookingRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookingrec
     *
     * @mbg.generated Mon Jun 28 15:47:04 CST 2021
     */
    long countByExample(BookingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookingrec
     *
     * @mbg.generated Mon Jun 28 15:47:04 CST 2021
     */
    int deleteByExample(BookingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookingrec
     *
     * @mbg.generated Mon Jun 28 15:47:04 CST 2021
     */
    int deleteByPrimaryKey(Long recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookingrec
     *
     * @mbg.generated Mon Jun 28 15:47:04 CST 2021
     */
    int insert(BookingRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookingrec
     *
     * @mbg.generated Mon Jun 28 15:47:04 CST 2021
     */
    int insertSelective(BookingRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookingrec
     *
     * @mbg.generated Mon Jun 28 15:47:04 CST 2021
     */
    List<BookingRecord> selectByExample(BookingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookingrec
     *
     * @mbg.generated Mon Jun 28 15:47:04 CST 2021
     */
    BookingRecord selectByPrimaryKey(Long recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookingrec
     *
     * @mbg.generated Mon Jun 28 15:47:04 CST 2021
     */
    int updateByExampleSelective(@Param("record") BookingRecord record, @Param("example") BookingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookingrec
     *
     * @mbg.generated Mon Jun 28 15:47:04 CST 2021
     */
    int updateByExample(@Param("record") BookingRecord record, @Param("example") BookingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookingrec
     *
     * @mbg.generated Mon Jun 28 15:47:04 CST 2021
     */
    int updateByPrimaryKeySelective(BookingRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookingrec
     *
     * @mbg.generated Mon Jun 28 15:47:04 CST 2021
     */
    int updateByPrimaryKey(BookingRecord record);
}