package org.kexie.bookshelfbackyard.model;

public class BookingRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookingrec.rec_id
     *
     * @mbg.generated Mon Jun 28 15:47:04 CST 2021
     */
    private Long recId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookingrec.uid
     *
     * @mbg.generated Mon Jun 28 15:47:04 CST 2021
     */
    private Long uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookingrec.rec_id
     *
     * @return the value of bookingrec.rec_id
     *
     * @mbg.generated Mon Jun 28 15:47:04 CST 2021
     */
    public Long getRecId() {
        return recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookingrec.rec_id
     *
     * @param recId the value for bookingrec.rec_id
     *
     * @mbg.generated Mon Jun 28 15:47:04 CST 2021
     */
    public void setRecId(Long recId) {
        this.recId = recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookingrec.uid
     *
     * @return the value of bookingrec.uid
     *
     * @mbg.generated Mon Jun 28 15:47:04 CST 2021
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookingrec.uid
     *
     * @param uid the value for bookingrec.uid
     *
     * @mbg.generated Mon Jun 28 15:47:04 CST 2021
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }
}