package org.kexie.bookshelfbackyard.model;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.stu_id
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    private String stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.name
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.mail
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.dept
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    private Integer dept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.loc
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    private Integer loc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.stu_id
     *
     * @return the value of members.stu_id
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.stu_id
     *
     * @param stuId the value for members.stu_id
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.name
     *
     * @return the value of members.name
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.name
     *
     * @param name the value for members.name
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.mail
     *
     * @return the value of members.mail
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.mail
     *
     * @param mail the value for members.mail
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.dept
     *
     * @return the value of members.dept
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    public Integer getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.dept
     *
     * @param dept the value for members.dept
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    public void setDept(Integer dept) {
        this.dept = dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.loc
     *
     * @return the value of members.loc
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    public Integer getLoc() {
        return loc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.loc
     *
     * @param loc the value for members.loc
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    public void setLoc(Integer loc) {
        this.loc = loc;
    }
}