package org.kexie.bookshelfbackyard.model;

public class UserWechat {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatUser.uid
     *
     * @mbg.generated Sat Sep 25 20:51:01 CST 2021
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatUser.openid
     *
     * @mbg.generated Sat Sep 25 20:51:01 CST 2021
     */
    private String openid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatUser.uid
     *
     * @return the value of wechatUser.uid
     *
     * @mbg.generated Sat Sep 25 20:51:01 CST 2021
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatUser.uid
     *
     * @param uid the value for wechatUser.uid
     *
     * @mbg.generated Sat Sep 25 20:51:01 CST 2021
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatUser.openid
     *
     * @return the value of wechatUser.openid
     *
     * @mbg.generated Sat Sep 25 20:51:01 CST 2021
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatUser.openid
     *
     * @param openid the value for wechatUser.openid
     *
     * @mbg.generated Sat Sep 25 20:51:01 CST 2021
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }
}