package org.kexie.bookshelfbackyard.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.uid
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.stu_id
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    private String stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.nickname
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.mail
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.type
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    private Byte type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.uid
     *
     * @return the value of users.uid
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.uid
     *
     * @param uid the value for users.uid
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.stu_id
     *
     * @return the value of users.stu_id
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.stu_id
     *
     * @param stuId the value for users.stu_id
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.nickname
     *
     * @return the value of users.nickname
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.nickname
     *
     * @param nickname the value for users.nickname
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.mail
     *
     * @return the value of users.mail
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.mail
     *
     * @param mail the value for users.mail
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.type
     *
     * @return the value of users.type
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.type
     *
     * @param type the value for users.type
     *
     * @mbg.generated Mon Jul 05 19:12:29 CST 2021
     */
    public void setType(Byte type) {
        this.type = type;
    }
}